# Generated by Django 5.1.15 on 2026-06-21 11:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morpheme', models.CharField(help_text='Корневая морфема, напр. ك\u200cت\u200cب.', max_length=64, verbose_name='Корень (арабица)')),
                ('transliteration', models.CharField(blank=True, help_text='Напр. k-t-b.', max_length=64, verbose_name='Транслитерация корня')),
                ('origin', models.CharField(choices=[('turkic', 'Тюркский'), ('arabic', 'Арабский'), ('persian', 'Персидский'), ('other', 'Другое')], default='turkic', max_length=16, verbose_name='Происхождение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Корень',
                'verbose_name_plural': 'Корни',
                'ordering': ['morpheme'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword_arabic', models.CharField(help_text='Аутентичное написание на арабской графике (насх).', max_length=255, verbose_name='Слово (арабица, насх)')),
                ('transliteration_latin', models.CharField(blank=True, max_length=255, verbose_name='Транслитерация (латиница)')),
                ('transliteration_cyrillic', models.CharField(blank=True, max_length=255, verbose_name='Транслитерация (кириллица)')),
                ('pronunciation', models.CharField(blank=True, max_length=255, verbose_name='Произношение (IPA / фонетика)')),
                ('part_of_speech', models.CharField(choices=[('noun', 'Существительное'), ('verb', 'Глагол'), ('adjective', 'Прилагательное'), ('adverb', 'Наречие'), ('pronoun', 'Местоимение'), ('numeral', 'Числительное'), ('particle', 'Частица'), ('conjunction', 'Союз'), ('postposition', 'Послелог'), ('interjection', 'Междометие'), ('phrase', 'Устойчивое выражение'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Часть речи')),
                ('definition', models.TextField(blank=True, help_text='Развёрнутое определение слова (в отличие от краткого перевода).', verbose_name='Толкование')),
                ('etymology', models.TextField(blank=True, verbose_name='Этимология')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись из публичного поиска (черновик / предложение на модерации).', verbose_name='Опубликовано')),
                ('norm_arabic', models.CharField(default='', editable=False, max_length=255)),
                ('norm_latin', models.CharField(default='', editable=False, max_length=255)),
                ('norm_cyrillic', models.CharField(default='', editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_words', to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='dictionary.root', verbose_name='Корень')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['headword_arabic'],
            },
        ),
        migrations.CreateModel(
            name='UsageExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_arabic', models.TextField(verbose_name='Пример (арабица)')),
                ('text_cyrillic', models.TextField(blank=True, verbose_name='Пример (кириллица)')),
                ('translation', models.TextField(blank=True, verbose_name='Перевод примера')),
                ('source', models.CharField(blank=True, help_text='Произведение, автор или ссылка на источник.', max_length=255, verbose_name='Источник')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictionary.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Пример использования',
                'verbose_name_plural': 'Примеры использования',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('tt', 'Татарский (совр.)'), ('tr', 'Турецкий')], default='ru', max_length=8, verbose_name='Язык')),
                ('text', models.CharField(max_length=500, verbose_name='Перевод')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dictionary.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=django.contrib.postgres.indexes.GinIndex(fields=['norm_arabic'], name='word_norm_arabic_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='word',
            index=django.contrib.postgres.indexes.GinIndex(fields=['norm_latin'], name='word_norm_latin_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='word',
            index=django.contrib.postgres.indexes.GinIndex(fields=['norm_cyrillic'], name='word_norm_cyrillic_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
